# Generated by Django 5.2.15 on 2026-06-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="품목코드"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="품목명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RAW", "원자재"),
                            ("SUB", "부자재"),
                            ("CONSUMABLE", "소모품"),
                            ("EQUIPMENT", "설비"),
                            ("OTHER", "기타"),
                        ],
                        default="RAW",
                        max_length=20,
                        verbose_name="분류",
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="EA", max_length=20, verbose_name="단위"),
                ),
                (
                    "standard_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="표준단가",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
            ],
            options={
                "verbose_name": "품목",
                "verbose_name_plural": "품목 목록",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="공급업체코드"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="공급업체명")),
                (
                    "business_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="사업자번호"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=50, verbose_name="담당자"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="주소")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
            ],
            options={
                "verbose_name": "공급업체",
                "verbose_name_plural": "공급업체 목록",
                "ordering": ["name"],
            },
        ),
    ]
